version: '1.0'

services:
  dev:
    container_name: authenticacion-service-dev
    image: authenticacion-service-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - authentication-service-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - ./.env
  prod:
    container_name: nestjs_api_prod
    image: authenticacion-service-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - authentication-service-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  authentication-service-network:
