name: Deploy Nestjs App

on:
  push:
   branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "spentrook" --password-stdin
        docker image build -t spentrook/authentication-service:latest .
        docker push spentrook/authentication-service:latest
